// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: tee_cert_service.proto

package certs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TeeCertClient is the client API for TeeCert service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TeeCertClient interface {
	NegotiateCert(ctx context.Context, in *TeeCertNegotiateRequest, opts ...grpc.CallOption) (*TeeCertNegotiateResponse, error)
}

type teeCertClient struct {
	cc grpc.ClientConnInterface
}

func NewTeeCertClient(cc grpc.ClientConnInterface) TeeCertClient {
	return &teeCertClient{cc}
}

func (c *teeCertClient) NegotiateCert(ctx context.Context, in *TeeCertNegotiateRequest, opts ...grpc.CallOption) (*TeeCertNegotiateResponse, error) {
	out := new(TeeCertNegotiateResponse)
	err := c.cc.Invoke(ctx, "/attest.TeeCert/NegotiateCert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TeeCertServer is the server API for TeeCert service.
// All implementations must embed UnimplementedTeeCertServer
// for forward compatibility
type TeeCertServer interface {
	NegotiateCert(context.Context, *TeeCertNegotiateRequest) (*TeeCertNegotiateResponse, error)
	mustEmbedUnimplementedTeeCertServer()
}

// UnimplementedTeeCertServer must be embedded to have forward compatible implementations.
type UnimplementedTeeCertServer struct {
}

func (UnimplementedTeeCertServer) NegotiateCert(context.Context, *TeeCertNegotiateRequest) (*TeeCertNegotiateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NegotiateCert not implemented")
}
func (UnimplementedTeeCertServer) mustEmbedUnimplementedTeeCertServer() {}

// UnsafeTeeCertServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TeeCertServer will
// result in compilation errors.
type UnsafeTeeCertServer interface {
	mustEmbedUnimplementedTeeCertServer()
}

func RegisterTeeCertServer(s grpc.ServiceRegistrar, srv TeeCertServer) {
	s.RegisterService(&TeeCert_ServiceDesc, srv)
}

func _TeeCert_NegotiateCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TeeCertNegotiateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeeCertServer).NegotiateCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/attest.TeeCert/NegotiateCert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeeCertServer).NegotiateCert(ctx, req.(*TeeCertNegotiateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TeeCert_ServiceDesc is the grpc.ServiceDesc for TeeCert service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TeeCert_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "attest.TeeCert",
	HandlerType: (*TeeCertServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NegotiateCert",
			Handler:    _TeeCert_NegotiateCert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tee_cert_service.proto",
}
